### ISSUE TITLE
Broken build when using monaco v0.34.1

### ISSUE THREAD

**Issue by noru** [vdesjs/vite-plugin-monaco-editor#40]
Seems something is wrong with the ".tff". Works fine using v0.33.0

```
✘ [ERROR] No loader is configured for ".ttf" files: ../../node_modules/.pnpm/monaco-editor@0.34.1/node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.ttf

    ../../node_modules/.pnpm/monaco-editor@0.34.1/node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.css:9:6:
      9 │   src: url(./codicon.ttf) format("truetype");
        ╵        ~~~~~~~~~~~~~~~~~~

dist/assets/codicon.71cccbf1.ttf                    70.80 KiB
dist/index.html                                     1.89 KiB
[vite-plugin-moncao-editor] Build failed with 1 error:
../../node_modules/.pnpm/monaco-editor@0.34.1/node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.css:9:6: ERROR: No loader is configured for ".ttf" files: ../../node_modules/.pnpm/monaco-editor@0.34.1/node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.ttf
error during build:
Error: Build failed with 1 error:
../../node_modules/.pnpm/monaco-editor@0.34.1/node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.css:9:6: ERROR: No loader is configured for ".ttf" files: ../../node_modules/.pnpm/monaco-editor@0.34.1/node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.ttf
    at failureErrorWithLog (/Users/zxiu/code/exp-builder-web/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:1566:15)
    at /Users/zxiu/code/exp-builder-web/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:1024:28
    at /Users/zxiu/code/exp-builder-web/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:969:67
    at buildResponseToResult (/Users/zxiu/code/exp-builder-web/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:1022:7)
    at /Users/zxiu/code/exp-builder-web/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:1134:14
    at responseCallbacks.<computed> (/Users/zxiu/code/exp-builder-web/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket (/Users/zxiu/code/exp-builder-web/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/Users/zxiu/code/exp-builder-web/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by blueluu** [comment]
update monaco-editor to 0.50.0 can solve it
